version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
  app:
    hostname: app
    build: ../backend/
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend/:/app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - '8000:8000'
    env_file:
      - ../backend/.env
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
    env_file:
      - ../backend/.env
    volumes:
      - ./var/postgres_data/:/var/lib/postgresql/data/:rw